services:
  api:
    ports:
      - "5050:8080"
    volumes:
      - ./backend/src/InstaClone.Api:/src
      - uploads:/app/uploads
    environment:
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    ports:
      - "4200:80"

  db:
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
